### PR TITLE
Implement useReduxStateMapped

### PR DESCRIPTION
**Pull request by dai-shi**
This is the one used in #16 with some modifications.
In the end, I didn't use Proxy.

I'll put the benchmark result later.

### CODE REVIEW

**Comment by dai-shi** [comment]
### react-redux 7.0.0-beta.0
```
┌─────────┬──────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                              │
│         │ (Mount, Avg) │                                                                         │
├─────────┼──────────────┼─────────────────────────────────────────────────────────────────────────┤
│ 40.41   │ 343.4, 0.4   │ 39,45,44,38,36,32,30,46,44,45,43,46,45,42,46,42,34,36,33,35,43,42,40,40 │
└─────────┴──────────────┴─────────────────────────────────────────────────────────────────────────┘
```

### useReduxState 3c5b017
```
┌─────────┬──────────────┬────────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                                 │
│         │ (Mount, Avg) │                                                                            │
├─────────┼──────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 20.60   │ 419.7, 0.3   │ 15,20,19,23,22,21,24,21,23,22,21,18,19,18,22,23,21,23,20,17,18,22,23,22,22 │
└─────────┴──────────────┴────────────────────────────────────────────────────────────────────────────┘
```

### useReduxStateMapped 3c5b017
```
┌─────────┬──────────────┬───────────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                                    │
│         │ (Mount, Avg) │                                                                               │
├─────────┼──────────────┼───────────────────────────────────────────────────────────────────────────────┤
│ 32.20   │ 224.2, 0.3   │ 18,37,32,28,30,28,27,38,34,28,34,35,36,32,30,35,32,30,28,30,32,36,40,33,27,27 │
└─────────┴──────────────┴───────────────────────────────────────────────────────────────────────────────┘
```

----

(Numbers are not very stable while running those tests.)

**Comment by dai-shi** [comment]
I want some feedbacks in the API design, but let me merge this first and release it.

**Comment by faceyspacey** [comment]
## API similar to Respond Framework:
> *except selectors don't need to be provided at store creation, and therefore no Redux fork required*

```js
import useRedux from 'reacitive-react-redux'

const selectors = {
   foo: (state, arg) => state[arg],
   bar: (state, arg, arg2) => state.baz[arg][arg2],
}
const { state, dispatch } = useRedux(selectors) // selectors are an optional arg
return <div>{state.foo(props.arg)} - {state.bar(props.arg, props.arg2)} - {state.baz}</div>
```

> so you have to implement this in **2 phases:** *`useRedux` + get argument dependencies from actual calls to selectors, which is most natural*


## Idea closer to your interface:

### single selector usage:

```js
import useRedux from 'reacitive-react-redux'

const mapState = (state, arg) => state[arg]
const deps = [props.arg]

const { state, dispatch, selector } = useRedux(mapState, deps)
return <div>{selector} - {state.baz}</div>
```

### multi-selector usage:

```js
import useRedux from 'reacitive-react-redux'

const stateMappers = {
   foo: (state, arg) => state[arg],
   bar: (state, arg, arg2) => state.baz[arg][arg2],
}

const deps = {
   foo: [props.arg],
   bar: [props.arg, props.arg2]
}

const { state, dispatch, selectors } = useRedux(stateMappers, deps)
return <div>{selectors.foo} - {selectors.bar} - {state.baz}</div>
```

**Comment by faceyspacey** [comment]
Here's a hypothetical implementation using `memoize-state` + some additional optimizations:

```js
import memoize from 'memoize-state'

export const useReduxStateMapped = (mapState, deps) => {
  const forceUpdate = useForceUpdate();
  // store&state
  const store = useContext(ReduxStoreContext);
  const state = store.getState();

  const lastMapState = useRef(null);
  const lastMapped = useRef(null);
  const triggeredByStore = useRef(false)

  // for best perf, keep single memoized function for duration of component life
  lastMapState.current = lastMapState.current || memoize(mapState)
  const memoizedSelector = lastMapState.current

  // for best perf, we need to know if the render occurred from props change or store change
  const mapped = triggeredByStore.current
    ? lastMapped.current // because we already have this from the subscription callback
    : (lastMapped.current = memoizedSelector(state, ...deps))

  // subscription
  useEffect(() => {
    const callback = () => {
      let changed;
      let mappedNew

      try {
        mappedNew = memoizedSelector(store.getState(), ...deps)
        changed = mappedNew === lastMapped.current
      } catch (e) {
        changed = true; // props are likely to be updated
      }

      if (changed) {
        // block duplicate call to `memoizedSelector` in subsequent re-render
        triggeredByStore.current = true
        lastMapped.current = mappedNew 

        forceUpdate();
      }
    };
    // run once in case the state is already changed
    callback();
    const unsubscribe = store.subscribe(callback);
    return unsubscribe;
  }, [store, forceUpdate]);

  triggeredByStore.current = false
  return lastMapped.current;
};
```

> So note: `memoize-state` for all its magic is relatively cheap, but certainly not free. We shouldn't call it any more times than we have to.

@theKashey what do you think?

**Comment by theKashey** [comment]
Does ^it^ work? Does it work better? It's a question you have to answer, not me :)

**Comment by faceyspacey** [comment]
thats not the question im asking. benchmarks will show that. i was asking for a quick glance at the implementation, and if the correct steps were followed. i'll take your focus on perf, as a *yes*. 

What about the **TODO**--i feel like perhaps `proxyequal` is overkill here. We need a custom one-off mechanism to see if the selector was used or conditionally unused (perhaps a proxy is also overkill and just a ***flag*** is all we need??)

**Comment by theKashey** [comment]
The only concern here, a big one, is with selectors memoization.
Once selector is memoized it would not access the props it might, and that would change a whole function behaviour - only top level _smoke_ checks would left, making comparison faster.
In the same time - selector level memoization mitigates any additional computation expences from Proxies.
So, yet again, everything depends on the code style.

**Comment by faceyspacey** [comment]
what do you mean by "code style"?

**Comment by theKashey** [comment]
How _properly_ a final user will follow out _guidelines_ and structure the code as we expect.

**Comment by faceyspacey** [comment]
its the same as selectors always were, except u can leave out the first `state` arg.

**Comment by theKashey** [comment]
👍 , the only concern is `...deps` and how to _type_ this code.
```js
function useReduxStateMapped<T extends any[], X>(mapState: (...deps: T) => X, deps: T) {
```
Would require TS v3, not sure about Flow.

Without spreading deps:
```js
function useReduxStateMapped<T, X>(mapState: (deps: T) => X, deps: T) {
```
Would work everywhere.

**Comment by faceyspacey** [comment]
Yea, good point. Forget flow. Only latest TS. I miss dynamic features when going to TS, but I hate more extra garbage like this: `T extends any[]`

...we need to add `State`

```js
function useReduxStateMapped<T, X>(mapState: (state: State, deps: T) => X, deps: T) {
```

**Comment by faceyspacey** [comment]
until last year a least, Flow didn't have call time type params. so they are probably out.

**Comment by dai-shi** [comment]
Thanks, guys.
I think I have three topics to cover.
1. The current naive implementation doesn't handle objects nicely. I assumed reselect or something without deep considerations, but it's not what we want. Let me work on this first.
2. store level selectors a.k.a. no closures. I understand the requirement, and I'll tackle it next.
3. hooks api design. I know mine is longWrodedNames and split hooks. This is out of my preference and design, but I see people like simple ones. I will take more time thinking about it and listening from others.

**Comment by dai-shi** [comment]
e5d3c40 for 1. Now, benchmark time.

**Comment by dai-shi** [comment]
## stockticker

### react-redux 7.0.0-beta.0
```
┌─────────┬──────────────┬────────────────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                                 │
│         │ (Mount, Avg) │                                                                            │
├─────────┼──────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 54.66   │ 270.1, 0.3   │ 49,56,55,58,56,53,57,53,55,58,56,53,55,53,57,56,55,56,52,54,57,54,53,51,51 │
└─────────┴──────────────┴────────────────────────────────────────────────────────────────────────────┘
```

### reactive-react-redux v1.7.0 useReduxState
```
┌─────────┬──────────────┬───────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                            │
│         │ (Mount, Avg) │                                                       │
├─────────┼──────────────┼───────────────────────────────────────────────────────┤
│ 27.01   │ 281.7, 0.3   │ 25,27,29,28,29,27,28,27,28,26,27,26,27,26,25,27,25,25 │
└─────────┴──────────────┴───────────────────────────────────────────────────────┘
```

### reactive-react-redux v1.7.0 useReduxStateMapped (with issues because of no memoization)
```
┌─────────┬──────────────┬────────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                     │
│         │ (Mount, Avg) │                                                                │
├─────────┼──────────────┼────────────────────────────────────────────────────────────────┤
│ 45.01   │ 168.8, 0.2   │ 29,48,47,44,45,44,45,46,47,45,46,48,47,46,45,44,45,48,44,43,43 │
└─────────┴──────────────┴────────────────────────────────────────────────────────────────┘
```

### reactive-react-redux e5d3c40 useReduxStateMapped
```
┌─────────┬──────────────┬─────────────────────────────────────────────────────────────┐
│ Avg FPS │ Render       │ FPS Values                                                  │
│         │ (Mount, Avg) │                                                             │
├─────────┼──────────────┼─────────────────────────────────────────────────────────────┤
│ 26.70   │ 314.2, 0.3   │ 23,29,28,27,29,27,28,27,29,27,28,25,26,27,25,27,25,27,24,24 │
└─────────┴──────────────┴─────────────────────────────────────────────────────────────┘
```

----

I didn't expect this decrease.
It might be better to take a step back a bit and learn the problem.

https://github.com/dai-shi/reactive-react-redux/issues/16#issuecomment-478311537
> how many times is `Pair` rendering when `${c.UPDATE_PAIR}_${sliceId}` is dispatched?

**Comment by dai-shi** [comment]
> 1. The current naive implementation doesn't handle objects nicely. I assumed reselect or something without deep considerations, but it's not what we want. Let me work on this first.

This should be implemented in a9c1298a1a64bfceb8f99b819f3d0a7e58878a3e.
But, the performance is interestingly the same as useReduxState.
I'm starting thinking this is not because of hooks vs classes, but proxy is just somehow difficult in this scenario.
To make it sure, I'll convert the benchmark for different hooks and see the result.

**Pull request merged**
